// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANqpC73qB4qqmFeQJAvk7oIZl3tf7fyZ8',
    appId: '1:402777818753:web:a1c86dc11f5bf844116f80',
    messagingSenderId: '402777818753',
    projectId: 'mednet-worflows',
    authDomain: 'mednet-worflows.firebaseapp.com',
    storageBucket: 'mednet-worflows.firebasestorage.app',
    measurementId: 'G-4DWKK1EM6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOA37nriFmuTP-ABazmZSg1BQght246Q8',
    appId: '1:402777818753:android:9969182f4a45ba6a116f80',
    messagingSenderId: '402777818753',
    projectId: 'mednet-worflows',
    storageBucket: 'mednet-worflows.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy3bvB9srOuLfOb12CJK_P61OyiTBg3IQ',
    appId: '1:402777818753:ios:67768a0ce3f73ce7116f80',
    messagingSenderId: '402777818753',
    projectId: 'mednet-worflows',
    storageBucket: 'mednet-worflows.firebasestorage.app',
    iosBundleId: 'com.example.mednet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy3bvB9srOuLfOb12CJK_P61OyiTBg3IQ',
    appId: '1:402777818753:ios:67768a0ce3f73ce7116f80',
    messagingSenderId: '402777818753',
    projectId: 'mednet-worflows',
    storageBucket: 'mednet-worflows.firebasestorage.app',
    iosBundleId: 'com.example.mednet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANqpC73qB4qqmFeQJAvk7oIZl3tf7fyZ8',
    appId: '1:402777818753:web:416dd7a1ad9fa3b6116f80',
    messagingSenderId: '402777818753',
    projectId: 'mednet-worflows',
    authDomain: 'mednet-worflows.firebaseapp.com',
    storageBucket: 'mednet-worflows.firebasestorage.app',
    measurementId: 'G-7NTBEBZKCG',
  );
}
